slack_workspace: str = ""
slack_email: str = ""
slack_password: str = ""
user_token: str = ""
user_key: str = ""

slack_workspace_label: str = "//input[@id='domain']"
slack_workspace_button: str = "//button[@data-qa='submit_team_domain_button']"
username_label: str = "//input[@id='email']"
password_label: str = "//input[@id='password']"
sign_in_button: str = "//button[@id='signin_btn']"
channel_button: str = "//span[contains(text(), 'button')]"
newest_post_slack_name: str = "(//a[@class='c-link c-message__sender_link '])[last()]"
reaction_bar_buttons: str = "(//div[@aria-expanded='false' and @role='listitem'])[last()]" \
                       "//div[@class='c-message_kit__reaction_bar c-reaction_bar c-reaction_bar--light']//button"
add_reaction_to_newest_post_button: str = "(//div[@class='c-message_kit__gutter'])[last()]" \
                                     "//button[@class='c-button-unstyled c-reaction_add c-reaction_add--light']"
search_emoji_label: str = "//input[@class='c-input_text p-emoji_picker__input']"
thumbs_up_button: str = "//button[@aria-label='thumbsup emoji']"
google_search_label: str = "//input[@class='gLFyf gsfi']"
google_news_tab: str = "//a[@data-sc='N']"
google_first_article_link: str = "(//div[@id='rcnt']//a)[1]"
google_first_article_name: str = "(//div[@class='JheGif nDgy9d'])[1]"
bq_day_quote: str = "(//h2[text()='Quote of the Day'])[1]//parent::node()//div[@class='clearfix']"
bq_love_quote: str = "(//h2[text()='Love Quote of the Day'])[1]//parent::node()//div[@class='clearfix']"
bq_art_quote: str = "(//h2[text()='Art Quote of the Day'])[1]//parent::node()//div[@class='clearfix']"
bq_nature_quote: str = "(//h2[text()='Nature Quote of the Day'])[1]//parent::node()//div[@class='clearfix']"
bq_funny_quote: str = "(//h2[text()='Funny Quote Of the Day'])[1]//parent::node()//div[@class='clearfix']"
google_weather_type_label: str = "//span[@class='vk_gy vk_sh']"
google_high_temp_label: str = "(//div[@id='wob_dp']//span[@class='wob_t'])[1]"
google_low_temp_label: str = "(//div[@id='wob_dp']//span[@class='wob_t'])[3]"
google_precipitation_label: str = "//span[@id='wob_pp']"
google_humidity_label: str = "//span[@id='wob_hm']"
google_wind_label: str = "//span[@id='wob_ws']"